<?php

use App\Model\TourismPlace;
use Illuminate\Database\Seeder;

class TourismPlacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tourism_places')->truncate();

        $data = [
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Monumen Nasional',
            	'description' => 'The National Monument is a 132 m tower in the centre of Merdeka Square, Central Jakarta, symbolizing the fight for Indonesia. It is the national monument of the Republic of Indonesia, built to commemorate the struggle for Indonesian independence.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Gambir, Central Jakarta City, Jakarta',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Jakarta History Museum',
            	'description' => 'The Jakarta History Museum, also known as Fatahillah Museum or Batavia Museum, is located in the Old Town of Jakarta, Indonesia. The building was built in 1710 as the Stadhuis of Batavia.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Taman Fatahillah No.1, Pinangsia, Tamansari, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11110',
            	'phone' => '(021) 6929101',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'National Monumen Indonesia',
            	'description' => 'The National Museum of Indonesia, is an archeological, historical, ethnological, and geographical museum located in Jalan Medan Merdeka Barat, Central Jakarta, right on the west side of Merdeka Square.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Medan Merdeka Barat No.12, Gambir, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10110',
            	'phone' => '(021) 3868172',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Wayang Museum',
            	'description' => 'The Wayang Museum is a museum dedicated to Javan wayang puppetry. The museum is located in Kota Tua, Jakarta, Indonesia.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Pintu Besar Utara No.27, RT.7/RW.6, Pinangsia, Tamansari, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11110',
            	'phone' => '(021) 6929560',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Museum MACAN (Modern and Contemporary Art in Nusantara)',
            	'description' => '',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'AKR Tower, Jalan Panjang No.5, Kebon Jeruk, RT.11/RW.10, Kb. Jeruk, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11530',
            	'phone' => '(021) 22121888',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Taman mini indonesia indah',
            	'description' => 'Taman Mini Indonesia Indah is a culture-based recreational area located in East Jakarta, Indonesia. It has an area of about 250 acres. Slogan: Kunjungi Taman Mini, Cintai Indonesia (Visit Taman Mini, Love Indonesia) Did you know: Taman Mini is the brainchild of the late Ibu Tien Soeharto, former Indonesian First Lady.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'East Jakarta City, Jakarta',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Museum of fine arts and ceramics',
            	'description' => 'The Museum of Fine Arts and Ceramics is a museum in Jakarta, Indonesia. The museum is dedicated especially to the display of traditional fine art and ceramics of Indonesia.                ',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Pos Kota, RT.9/RW.2, Daerah Khusus Ibukota Jakarta, Jakarta Barat, West Jakarta City, Jakarta 11110',
            	'phone' => '(021) 6926090',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'National gallery of indonesia',
            	'description' => 'The National Gallery of Indonesia is a museum and an art gallery in Jakarta, Indonesia. The National Gallery of Indonesia has existed as a cultural institution in the field of visual arts since May 8, 1999.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'East Jakarta City, Jakarta',
            	'phone' => '(021) 34833954',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Jakarta planetarium and observatory',
            	'description' => 'Jakarta Planetarium and Observatory is a public planetarium and an observatory, part of the Taman Ismail Marzuki art and science complex in Jakarta, Indonesia. The planetarium is the oldest of the three planetaria in Indonesia.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Cikini Raya No.73, RT.8/RW.2, Cikini, Menteng, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10330',
            	'phone' => '(021) 2305146',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Textile museum',
            	'description' => 'The Textile Museum is a museum in Palmerah, West Jakarta, Indonesia. The museum houses a collection of textiles from various islands in Indonesia.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Aipda Ks. Tubun Raya No.2-4, RT.4/RW.2, Kota Bambu Sel., Palmerah, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11420',
            	'phone' => '(021) 5606613',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Museum Bank Indonesia',
            	'description' => 'Bank Indonesia Museum is a bank museum located in Jakarta, Indonesia. It was founded by Bank Indonesia and opened on 21 July 2009.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Pintu Besar Utara No.3, RT.3/RW.6, Pinangsia, Tamansari, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11110',
            	'phone' => '(021) 2600158',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Setu Babakan',
            	'description' => 'Setu Babakan or Lake Babakan (Setu or Situ means Small Lake) is located in Srengseng Sawah, Sub-district of Jagakarsa, Municipality of South Jakarta, Indonesia near Depok or around 5 kilometers southeast of Ragunan Zoo at the center of the Betawi Cultural Village, a site considered part of the cultural heritage of Jakarta, which is devoted to the preservation of the indigenous Betawi culture.[1] The location of the Betawi Cultural Village is replacement of the previous Condet (Betawi) Cultural Village which is eroded by the time.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Alive Museum Ancol',
            	'description' => '',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Ancol Beach City Mall, 3rd Floor, Jalan Ancol Beach City, Ancol, Pademangan, Ancol, Pademangan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14430',
            	'phone' => '(021) 29388143',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Istiqlal Mosque',
            	'description' => 'Istiqlal Mosque in Jakarta, Indonesia is the largest mosque in Southeast Asia and the third largest Sunni mosque in term of capacity.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Taman Wijaya Kusuma, Ps. Baru, Sawah Besar, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10710',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Cathedral',
            	'description' => 'also the seat of the Roman Catholic Archbishop of Jakarta, currently Archbishop Ignatius Suharyo Hardjoatmodjo.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Katedral No.7B, Ps. Baru, Sawah Besar, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10710',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Dian Al-Mahri Mosque',
            	'description' => 'Dian Al-Mahri Mosque, also known as Golden Dome Mosque, is a mosque built on the edge of Raya street, Depok City in West Java, Indonesia. Wikipedia',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Raya Meruyung, Meruyung, Limo, Meruyung, Limo, Kota Depok, Jawa Barat 16515',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Utung Jawa',
            	'description' => 'Utung Jawa is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pramuka Island',
            	'description' => 'Pramuka is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Tidung',
            	'description' => 'Tidung is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Macan',
            	'description' => 'Macan is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Bidadari',
            	'description' => 'Bidadari is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Kotok',
            	'description' => 'Kotok is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Sepa',
            	'description' => 'Sepa is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Kelor',
            	'description' => 'Kelor is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Air',
            	'description' => 'Air is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Pulau Papatheo',
            	'description' => 'Papatheo  is an island in the Thousand Islands archipelago. The archipelago lies in the western part of the Java Sea and is located north of Indonesia capital Jakarta.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Ragunan zoo',
            	'description' => 'Ragunan Zoo is a 140-hectare zoo located in Pasar Minggu, South Jakarta, Indonesia. It is a zoo that has an aviary and included a primate centre, and employs over 450 people.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Harsono No.1, Ragunan, Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta',
            	'phone' => '(021) 78847114',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Sea World Indonesia',
            	'description' => 'Sizable, contemporary aquarium with sharks, various feeding shows, a touch tank & concessions.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Lodan Timur No.7, RW.10, Ancol, Pademangan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14430',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Jakarta Aquarium',
            	'description' => 'Neo SOHO Floor LG 101 - LGM 101, Jalan Letjen S. Parman No.28, Tanjung Duren Selatan, Grogol petamburan, Jakarta Barat, Daerah Khusus Ibukota Jakarta 11470',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '(021) 78847114',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Taman Wisata Alam Mangrove',
            	'description' => 'Ragunan Zoo is a 140-hectare zoo located in Pasar Minggu, South Jakarta, Indonesia. It is a zoo that has an aviary and included a primate centre, and employs over 450 people.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Garden House, RT.8/RW.1, Kamal Muara, Penjaringan, RT.6/RW.2, Kamal Muara, Penjaringan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14470',
            	'phone' => '(021) 29033066',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Taman Ayodya',
            	'description' => '',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
                'address' => 'Jalan Lamandau III, Kebayoran Baru, Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12130',
                'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Taman Rekreasi Wiladatika Cibubur',
            	'description' => '',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Pratidina No.6, Harjamukti, Cimanggis, Kota Depok, Jawa Barat 16454',
            	'phone' => '',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Ocean Dream Samudra',
            	'description' => 'Aquatic-themed park featuring an underwater theater, fish tanks & performing sea-animal shows.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Lodan Timur No.7, RW.10, Ancol, Pademangan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14430',
            	'phone' => '(021) 2922222',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Snow Bay Waterpark TMII',
            	'description' => 'Waterpark with a range of rides & attractions, including pools, tubing & slides.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Komplek Taman Mini Indonesia Indah, kel : Ceger, kec : Cipayung, Jalan Taman Mini Indonesia Indah, Pinang Ranti, Makasar, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13820',
            	'phone' => '(021) 87783530',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Atlantis Water Adventure',
            	'description' => 'Sizable waterpark with lots of greenery & attractions such as a wave pool & floating playground.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Taman Impian Jaya Ancol, Jl. Lodan Timur No. 7, Ancol, Pademangan, RW.10, Ancol, Pademangan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14430',
            	'phone' => '(021) 29222222',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Waterbom Jakarta',
            	'description' => 'Expansive, manicured water park renowned for lots of winding slides, pools & family-friendly fun.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'pantai indah kapuk, Jalan Pantai Indah Barat No.1, RT.7/RW.2, Kamal Muara, Penjaringan, RT.7/RW.2, Kamal Muara, Penjaringan, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14470',
            	'phone' => '(021) 55966666',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Kidzania Pacific Place',
            	'description' => '',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Pacific Place L6 - 601 Sudirman Central Business, Jalan Jendral Sudirman No.52-53, Senayan, Kebayoran Baru, RT.5/RW.3, Senayan, Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12190',
            	'phone' => '(021) 5154888',
            	'status' => 'active'
            ],
            [
                'city_id' => 515,
            	'category' => '',
            	'name' => 'Kalijodo Park',
            	'description' => 'Kalijodo Park, is a newly inaugurated urban park at Penjaringan, Jakarta, Indonesia.The park has a land area of 3.4 hectares and located by the side of Krendang River, which was formally opened on 22 February 2017.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => '',
            	'phone' => '',
            	'status' => 'active'
            ],

            [
                'city_id' => 227,
            	'category' => '',
            	'name' => 'Taman Sari',
            	'description' => 'Taman Sari Yogyakarta atau Taman Sari Keraton Yogyakarta adalah situs bekas taman atau kebun istana Keraton Ngayogyakarta Hadiningrat, yang dapat dibandingkan dengan Kebun Raya Bogor sebagai kebun Istana Bogor. Wikipedia',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Komplek Wisata Taman Sari, Taman, Patehan, Kraton, Patehan, Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55133',
            	'phone' => '0817-265-343',
            	'status' => 'active'
            ],
            [
                'city_id' => 227,
            	'category' => '',
            	'name' => 'Keraton Yogyakarta',
            	'description' => 'Keraton Ngayogyakarta Hadiningrat atau Keraton Yogyakarta merupakan istana resmi Kesultanan Ngayogyakarta Hadiningrat yang kini berlokasi di Kota Yogyakarta, Daerah Istimewa Yogyakarta, Indonesia. Wikipedia',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Rotowijayan Blok No. 1, Panembahan, Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta',
            	'phone' => '(0622) 74373721',
            	'status' => 'active'
            ],
            [
                'city_id' => 227,
            	'category' => '',
            	'name' => 'Alun-alun kidul Yogyakarta',
            	'description' => 'Lapangan berumput di belakang istana kerajaan ini menjadi lokasi rekreasi ramai pada siang & malam.',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jl. Alun Alun Kidul, Patehan, Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55133',
            	'phone' => '(0622) 74373721',
            	'status' => 'active'
            ],
            [
                'city_id' => 227,
            	'category' => '',
            	'name' => 'Candi Prambanan',
            	'description' => 'Candi Prambanan atau Candi Roro Jonggrang adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9 masehi. Wikipedia',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Bokoharjo, Kec. Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta',
            	'phone' => '(0274) 496401',
            	'status' => 'active'
            ],
            [
                'city_id' => 227,
            	'category' => '',
            	'name' => 'Monumen Jogja Kembali',
            	'description' => 'Museum Monumen Yogya Kembali, adalah sebuah museum sejarah perjuangan kemerdekaan Republik Indonesia yang ada di kota Yogyakarta dan dikelola oleh Departemen Kebudayaan dan Pariwisata. Wikipedia
                Alamat: Jalan Ring Road Utara, Sari Harjo, Ngaglik, Sariharjo, Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
                'adult_price' => '',
                'child_price' => '',
                'infant_price' => '',
            	'tourist_price' => '',
            	'longitude' => 1,
            	'latitude' => -1,
                'facilities' => '',
            	'rate' => 1,
            	'address' => 'Jalan Ring Road Utara, Sari Harjo, Ngaglik, Sariharjo, Ngaglik, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55581',
            	'phone' => '(0274) 868225',
            	'status' => 'active'
            ],
        ];

        TourismPlace::insert($data);
    }
}
